name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo sources into VM
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Install NPM dependencies
        run: npm ci
      - name: Check source code formatting
        run: npm run format:check
      - name: Run automated tests
        env:
          CI: true
        run: npm test -- --coverage
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
        run: npx surge --project ./build --domain fearful-birth.surge.sh
