name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo sources into VM
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Updates node  ver
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules # Folder to cache
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('**/package-lock.json') }} ## Key for the cached folder.
          #restore-keys: ${{ runner.os }}-npm-deps-
      - name: Print working directory
        run: pwd
      - name: Install NPM dependencies
        #        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }} # Evaluate expression
        run: npm ci
      - name: Check source code formatting
        run: npm run format:check
      - name: Run automated tests
        env:
          CI: true
        run: npm test -- --coverage
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: npx surge --project ./build --domain fearful-birth.surge.sh
